image: docker:latest

stages:
  - test
  - publish

services:
  - docker:dind

before_script:
  - docker info
  - docker login -p $ARTIFACTORY_PASSWORD -u $ARTIFACTORY_USERNAME edify-dkr.jfrog.io

test-debug:
  image: openjdk:8
  stage: test
  script:
    - ./gradlew build --stacktrace -PexcludeTests=org/commonlibrary/cllo/services/ElasticSearchServiceSpec -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD -Partifactory_contextUrl=https://edify.artifactoryonline.com/edify

release-docker:
  image: openjdk:8
  stage: publish
  only:
    - master
  script:
    - ./gradlew build --stacktrace -x test -x sourcesJar -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD -Partifactory_contextUrl=https://edify.artifactoryonline.com/edify
    - docker build -t cl-lo .
    - export DOCKER_TAG=`cat version`
    - docker tag cl-lo edify-dkr.jfrog.io/cl-lo:$DOCKER_TAG
    - docker push edify-dkr.jfrog.io/cl-lo
