stages:
  - test
  - publish

test-debug:
  image: openjdk:8
  stage: test
  script:
    - ./gradlew build --stacktrace -PexcludeTests=org/commonlibrary/cllo/services/ElasticSearchServiceSpec -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD -Partifactory_contextUrl=https://edify.artifactoryonline.com/edify

release-docker:
  image: openjdk:8
  stage: publish
  only:
    - master
  script:
    - echo "Docker-image publication pending..."
