spring:
  profiles.active: default,BE_Mongo,FS_S3,SRCH_ES
---
info:
  build:
    artifact: cl-lo
    version: 0.0.1
    description: Common Library Learning Object Microservice

server:
  port: ${CL_LO_HTTPS_PORT}
  ssl:
    keyStore: ${CERT_KEY_STORE_PATH}
    keyStorePassword: ${CERT_KEY_STORE_PW}
    keyPassword: ${CERT_KEY_PW}

http-server:
  port: ${CL_LO_HTTP_PORT}

spring:
  profiles: default
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.generate_statistics: true
  data:
    mongodb:
      uri: ${CL_MONGO_URI}

database:
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
  url: postgres://myuser:mypwd@localhost:5432/mydb

elastic_search:
  general:
    lo_index: clc_learning_object_index
    lo_type: clc_learning_object
    http:
      url: ${CL_ES_URL}
    binary:
      host: ${CL_ES_HOST}
      port: ${CL_ES_PORT}
  more_like_this:
    min_doc_freq: 1
    min_term_freq: 1
    minimum_should_match: 30%

s3Storage:
  general:
    empty_bucket: false
    bucket_name: ${AWS_S3_BUCKET_NAME}
    aws_access_key: ${AWS_ACCESS_KEY}
    aws_secret_key: ${AWS_SECRET_KEY}
  file:
    url:
      expiration_hours: 2

api:
  base:
    url: /api/v1

rabbitmq:
  general:
    url: ${CL_RMQ_URL}
    lo_queue: cl_lo_queue

curricula:
  general:
    base_url: ${CL_CURRICULA_BASE_URL}
    api_url: ${CL_CURRICULA_API_URL}
    api_key_id: ${CL_CURRICULA_API_ID}
    api_secret_key: ${CL_CURRICULA_API_SECRET}

---
spring:
  profiles: Integration_Tests
  data:
    mongodb:
      uri: ${CL_IT_MONGO_URI}
